### ISSUE TITLE
Gameplay 1 : définir les zones de perte de controle (trop haut / trop bas )

### ISSUE THREAD

**Issue by Sebajuste** [Sebajuste/GlideToNewYork#3]

**Comment by PatrickPIGNOL** [comment]
Pour un planeur, tu n’es jamais trop haut parce que tu peux descendre en piqué. 
Par contre, tu peux être trop bas et ne pas pouvoir remonter parce qu'un planeur n'as pas de moteur.
La seule raison pour être trop haut serait un plafond radar pour ne pas être repéré. Mais les planeurs sont des objets relativement petits et peu visibles au radar, à moins qu'ils aient un transpondeur, au quel cas ils sont visibles même sans couverture radar.
